// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0G_xWUnilSLemuQZ-A2VWVuPR2MIggbQ',
    appId: '1:321222014653:web:9b5c49041f3502da44a9d4',
    messagingSenderId: '321222014653',
    projectId: 'tugasbesar01-ian',
    authDomain: 'tugasbesar01-ian.firebaseapp.com',
    storageBucket: 'tugasbesar01-ian.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLGAc2IcUJ4hJ7gS-pYh3c2x978iuRI-8',
    appId: '1:321222014653:android:bbcbe344086d41fd44a9d4',
    messagingSenderId: '321222014653',
    projectId: 'tugasbesar01-ian',
    storageBucket: 'tugasbesar01-ian.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACy7exk6_Ipx5S3hr3HeBtifPFPdrm5Bs',
    appId: '1:321222014653:ios:d126d2fa9c416c7b44a9d4',
    messagingSenderId: '321222014653',
    projectId: 'tugasbesar01-ian',
    storageBucket: 'tugasbesar01-ian.firebasestorage.app',
    iosBundleId: 'com.example.tugasbesar01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACy7exk6_Ipx5S3hr3HeBtifPFPdrm5Bs',
    appId: '1:321222014653:ios:d126d2fa9c416c7b44a9d4',
    messagingSenderId: '321222014653',
    projectId: 'tugasbesar01-ian',
    storageBucket: 'tugasbesar01-ian.firebasestorage.app',
    iosBundleId: 'com.example.tugasbesar01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0G_xWUnilSLemuQZ-A2VWVuPR2MIggbQ',
    appId: '1:321222014653:web:247943579144980944a9d4',
    messagingSenderId: '321222014653',
    projectId: 'tugasbesar01-ian',
    authDomain: 'tugasbesar01-ian.firebaseapp.com',
    storageBucket: 'tugasbesar01-ian.firebasestorage.app',
  );
}
